name: Update translation files

on:
  push:
    branches:
      - main
    paths:
      - '**.vala'
      - 'data/launcher.desktop.in'
      - 'data/metainfo.appdata.xml.in'
      - 'po/LINGUAS'
      - 'po/POTFILES.in'
      - 'po/extra/LINGUAS'
      - 'po/extra/POTFILES.in'
      - '.github/workflows/gettext.yml'

permissions:
  contents: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Install deps
        run: |
          sudo dnf update -y
          sudo dnf install -y \
            appstream-devel \
            gettext-devel \
            git \
            gtk4-devel \
            libadwaita-devel \
            libxml2-devel \
            meson \
            vala

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          rm -rf _build
          meson _build
          ninja -C _build

      - name: Regenerate translation files
        run: |
          ninja -C _build com.cassidyjames.dippi-pot
          ninja -C _build com.cassidyjames.dippi-update-po

      - name: Commit
        continue-on-error: true
        run: |
          # FILES_CHANGED=$(git diff --name-only | wc -l)
          # if [[ $FILES_CHANGED != 0 ]]; then
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update translation files"
          git push
          # fi
